### ISSUE TITLE
game dont start

### ISSUE THREAD

**Issue by dhgameryt** [JDKDigital/fuelgoeshere#1]
using fuelgoeshere-1.19.2-0.1.0.0.jar
 and forge 1.19.2 43.2.3 (it dont generate crash report)
[2022-12-31-6.log](https://github.com/JDKDigital/fuelgoeshere/files/10328234/2022-12-31-6.log)

**Comment by JaisDK** [comment]
Seems to be an incompatibility with AoA3

**Comment by Xplodin** [comment]
will this ever be fixed on 1.20.1?
aoa still doesnt work with this mod
