### ISSUE TITLE
Does not work with Iron Furnaces

### ISSUE THREAD

**Issue by James103** [JDKDigital/fuelgoeshere#2]
To reproduce:

1. Install Fuel Goes Here 1.19.2-0.1.0.0
2. Install Iron Furnaces 3.6.3
3. Create a new world with cheats enabled
4. Give yourself a furnace from Iron Furnaces
5. Shift-click coal or charcoal into the furnace GUI for a furnace from Iron Furnaces.
6. If a smelting recipe exists that costs coal or charcoal, the item goes into the input, not the fuel, despite this mod being installed. The mod works correctly for vanilla Furnaces.

Originally reproduced on modpack "All the Mods 8" version 1.0.9.

**Comment by JaisDK** [comment]
I know, I don't want to mixin into a mod, this only fixes the vanilla handler. Iron Furnaces duplicate the vanilla code so they will have to implement this in their own furnaces if they want to.
