### ISSUE TITLE
gross mixin usage (incompat with mods)

### ISSUE THREAD

**Issue by VaporeonScripts** [JDKDigital/fuelgoeshere#4]
https://mclo.gs/GqmOTRY

**Comment by VaporeonScripts** [comment]
https://github.com/Tslat/Advent-Of-Ascension/issues/4488

**Comment by JaisDK** [comment]
such wording

just remove this mod

**Comment by VaporeonScripts** [comment]
mb, just saying it could use better mixins :D, sorry again :sob:

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/64b23900-a600-4d39-8504-3100811d5ea4)
(if that could help somehow with a future fix(ig)?)

**Comment by Tslat** [comment]
![image](https://github.com/user-attachments/assets/43658d3a-dc63-497a-b10d-f0f4c1f8c3fd)

**Comment by JaisDK** [comment]
👍 I'll try it out

**Comment by JaisDK** [comment]
new version is up
the proposed code almost worked, it had to be `return false` not true

**Comment by VaporeonScripts** [comment]
Yippie

**Comment by TheBedrockMaster** [comment]
Awesome, tested and it works great :)
